name: task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.2

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.0
  http: ^0.13.6
  app_links: ^3.4.3
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
