// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOQbNStKDWEiM4C19M2QM213J2T_ObQUw',
    appId: '1:499405900954:web:e2db239c273f8e910ee323',
    messagingSenderId: '499405900954',
    projectId: 'jithvar-interview-task',
    authDomain: 'jithvar-interview-task.firebaseapp.com',
    storageBucket: 'jithvar-interview-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK1V58NL0Fef38PeJar-OzDIf_Ch6flCI',
    appId: '1:499405900954:android:94a9a925c35c08780ee323',
    messagingSenderId: '499405900954',
    projectId: 'jithvar-interview-task',
    storageBucket: 'jithvar-interview-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFUTFXMVFjnTj11ng0veCo25FCQzYlu2M',
    appId: '1:499405900954:ios:18ecf88264c34c1c0ee323',
    messagingSenderId: '499405900954',
    projectId: 'jithvar-interview-task',
    storageBucket: 'jithvar-interview-task.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFUTFXMVFjnTj11ng0veCo25FCQzYlu2M',
    appId: '1:499405900954:ios:18ecf88264c34c1c0ee323',
    messagingSenderId: '499405900954',
    projectId: 'jithvar-interview-task',
    storageBucket: 'jithvar-interview-task.appspot.com',
    iosBundleId: 'com.example.task',
  );
}
